name: Robô de Relatórios Diários

on:
  schedule:
    # Roda todo dia às 11:00 UTC (08:00 no horário de Brasília)
    - cron: '0 11 * * *'
  workflow_dispatch: # Permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Robot Script
        env:
          INTRANET_USER: ${{ secrets.INTRANET_USER }}
          INTRANET_PASSWORD: ${{ secrets.INTRANET_PASSWORD }}
          GOOGLE_SHEET_URL: ${{ secrets.GOOGLE_SHEET_URL }}
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
        run: python robo.py
